name: Build Go Code
on: [pull_request]

jobs:
  build:
    name: Windows Test
    runs-on: windows-2019
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go 1.23
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

        # Caching seems to really slow down the build due to the time
        # taken to save the cache.
        cache: false
      id: go
    - name: Build
      if: always()
      env:
        CC: x86_64-w64-mingw32-gcc
        CGO_ENABLED: 1
      shell: bash
      run: |
        go build ./examples/tracer/
